# Site settings
title: "Bryan Mark F. Fajutag"
description: "My resume hosted via Github Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Bryan Mark F. Fajutag"
resume_title:                   "Backend Developer"
resume_contact_email:           "fbryanmark@gmail.com"
resume_contact_telephone:       "+(63)-947-480-0629"
resume_contact_address:         "Batangas City, Philippines"
resume_header_contact_info:     "Batangas City, Philippines  | fbryanmark@gmail.com"
resume_header_intro:            "<p>An intermediate Ruby on Rails developer with years of experience in web development, who has participated in several projects.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/brynmrk"
  resume_linkedin_url:          "https://www.linkedin.com/in/bryanmarkfajutag"
  resume_website_url:           "https://resume.bryanmarkf.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
